pipeline {
    agent any

    environment {
        git_branch = 'master'
        git_url    = 'https://github.com/Neeraj999999/Amazon-ABC.git'
    }

    tools {
        maven 'MavenLocal'
        jdk   'JDK21'
    }

    stages {

        stage('clone project') {
            steps {
                git branch: "${git_branch}", url: "${git_url}"
            }
        }

        stage('clean') {
            steps {
                dir('Amazon') {
                    sh 'mvn clean'
                }
            }
        }

        stage('compile') {
            steps {
                dir('Amazon') {
                    sh 'mvn compile'
                }
            }
        }

        stage('test') {
            steps {
                dir('Amazon') {
                    sh 'mvn test'
                }
            }
        }

        stage('build') {
            steps {
                dir('Amazon') {
                    sh 'mvn clean install'
                }
            }
        }
    }

    post {

        success {
            mail to: 'neerajmishra91011@gmail.com',
                 subject: "SUCCESS: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                 body: """Hello Neeraj,

Your Jenkins pipeline build has SUCCESSFULLY completed.

Job Name : ${env.JOB_NAME}
Build No : ${env.BUILD_NUMBER}
Status   : SUCCESS

Console Output:
${env.BUILD_URL}console

Regards,
Jenkins CI Server
"""
        }

        failure {
            mail to: 'neerajmishra91011@gmail.com',
                 subject: "FAILURE: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                 body: """Hello Neeraj,

Your Jenkins pipeline build has FAILED.

Job Name : ${env.JOB_NAME}
Build No : ${env.BUILD_NUMBER}
Status   : FAILURE

Console Output:
${env.BUILD_URL}console

Regards,
Jenkins CI Server
"""
        }

        always {
            echo 'Post action completed.'
        }
    }
}
